### ISSUE TITLE
Discord link is invalid

### ISSUE THREAD

**Issue by NukeManDan** [noncesense-research-lab/archival_network#50]
Hey all 😁  I see that the discord link on the readme is broke... care to post a new one? 🙏🏼

**Comment by Mitchellpkt** [comment]
Good catch, thanks. [discord.noncesense.org](http://discord.noncesense.org)

**Comment by Mitchellpkt** [comment]
Fixed in 1aaecf5b39beb61c3e796796bee920a061a30352
